export const INSTRUMENT_TYPE = {
    GUITAR: 'GUITAR',
    UKULELE: 'UKULELE',
    PIANO: 'PIANO',
    CHORD_NAME_ONLY: '***',
}

export const INSTRUMENT_TABS = [
    INSTRUMENT_TYPE.GUITAR,
    INSTRUMENT_TYPE.UKULELE,
    INSTRUMENT_TYPE.PIANO,
    INSTRUMENT_TYPE.CHORD_NAME_ONLY,
]